on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # goreleaser docs say to use 0
      - name: Fetch the tags
        run: git fetch --force --tags
      - name: Set up Go so we can build the binary
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          cache: true
      - name: Build and publish the release binary and checksums.txt
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
